### ISSUE TITLE
.github/workflows have Cloudquery specific github actions secrets in them

### ISSUE THREAD

**Issue by andrewthetechie** [cloudquery/cq-provider-template#69]
### Describe the Bug
When generating a new provider from this template, cloudquery specific github actions secrets in them. Some examples:
* https://github.com/cloudquery/cq-provider-template/blob/main/.github/workflows/release-pr.yml#L17
* https://github.com/cloudquery/cq-provider-template/blob/main/.github/workflows/test_integration.yml#L111

These secrets are not documented anywhere which causes a freshly generated provider repo's CI to fail.

### Expected Behavior
CI should pass on a repo generated from the template OR these variables should be documented as a requirement to using the repo.

### CloudQuery Version
n/a

### Debug Output
n/a

### Steps to Reproduce
1. Generate a new github repo from this templated outside of the cloudquery org
2. Watch Actions

**Comment by erezrokah** [comment]
Great catch @andrewthetechie! We got carried a bit with our automation. This is fixed in https://github.com/cloudquery/cq-provider-template/pull/70
